  name: CI/CD
  on:
    push:
      branches:
        - main
  jobs:
    build:
      name: Build & deploy (Simulation)
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install Node
          uses: actions/setup-node@v2
          with:
            node-version: 16
        - name: Install packages
          run: npm i
        - name: Deploy
          run: npm run deploy
